### PR TITLE
Please don't merge - work in progress: Highlight technologies

### PR DESCRIPTION
**Pull request by kkoutoup**
Project#show
-Project technologies (as selected on instance creation) are highlighted when page loads
-Data object with form info available through js
Pending: how do i send this info back to the controller to update the instance
@Haumer @Vishal151 @E-F-J

### CODE REVIEW

**Comment by kkoutoup** [comment]
will try an alternative, simpler way

**Comment by Haumer** [comment]
Sorry didnt get to this yesterday @kkoutoup is this resolved or shall I take a sneakpeak!?

**Comment by kkoutoup** [comment]
Hi @Haumer Sahar suggested i don't do it with JS but with HTML instead which i'll try to implement. I also need some help with filtering results on our projects#index page. Not sure how to tackle it.

**Comment by Haumer** [comment]
yes, the non-js way is definitely the way to go, less complicated at the very least xD

**Pull request closed without merging**
